### ISSUE TITLE
__add__ with floating point values

### ISSUE THREAD

**Issue by Bchass** [Bchass/tinynumpy#15]
**Describe the bug**
It's currently not possible for `__add__' to interpret a floating point values as an integer  

**To Reproduce**
```python3
a = tnp.array([1,2,3])
result = a + 1.5
TypeError: 'float' object cannot be interpreted as an integer
```

**Expected behavior**
```python3
a = tnp.array([1,2,3])
result = a + 1.5
[2.5 3.5 4.5]
```

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Bchass** [comment]
This will also fix test cases for `__truediv__`.

**Comment by namitha01m** [comment]
Hi, I can solve this
